project("Editor")
    location(path.join(g_wkslight.workspacedir, "%{prj.name}"))
    targetdir(g_wkslight.targetdir)
    kind("ConsoleApp")
    language("C++")
    debugdir("")
    debugargs({
        --"--foobar",
    })
    files({
        "src/**.h",
        "src/**.cpp",
    })
    includedirs({
        "src",
    })
    g_wkslight.libs({
        "ExampleStaticLib",
    })